# Generated by Django 5.1.2 on 2024-10-20 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyweathersummary',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
