# Generated by Django 5.1.2 on 2024-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dailyweathersummary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweathersummary',
            name='curr_temp',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='avg_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='max_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='min_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='feels_like',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
