# Generated by Django 5.1.2 on 2024-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_dailyweathersummary_curr_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
