# Generated by Django 5.1.2 on 2024-10-20 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dailyweathersummary_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 15, 5, 54, 124651, tzinfo=datetime.timezone.utc)),
        ),
    ]
