# Generated by Django 5.1.2 on 2024-10-20 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_dailyweathersummary_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyweathersummary',
            name='datetime',
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 20)),
        ),
    ]
