# Generated by Django 5.1.2 on 2024-10-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_dailyweathersummary_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='weather_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
