# Generated by Django 5.1.2 on 2024-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_weatherdata_weather_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('weathercondition', models.CharField(max_length=50)),
            ],
        ),
    ]
