# Generated by Django 5.1.2 on 2024-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_weatheralerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheralerts',
            name='alertstring',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
