# Generated by Django 5.1.2 on 2024-10-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_weatheralerts_alertstring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralerts',
            name='weatherstring',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
